---
# tasks file for roles/install_graylog
#  - name: Install docker
#    include_tasks: install_docker.yml


  - name: Install Graylog
    include_tasks: install_graylog.yml

  - name: Install monitoring
    include_tasks: install_monitoring.yml

  - name: Install sert
    include_tasks: install_sert.yml

  - name: Install nginx
    include_tasks: install_nginx.yml

